### ISSUE TITLE
Sell steps are not being passed onto the API

### ISSUE THREAD

**Issue by mamash** [rentorm/3commas-api-node#2]
Sell steps (e.g. in a Smart Trade) are not being passed on the 3C API properly. Given a JSON object that contains e.g.

```
{ ...
  take_profit_type: 'step_sell',
  take_profit_step_orders:
   [ { percent: 40, price: 0.000062, price_method: 'bid' },
     { percent: 30, price: 0.000069, price_method: 'bid' },
     { percent: 20, price: 0.000074, price_method: 'bid' },
     { percent: 10, price: 0.000080, price_method: 'bid' } ],
... }
```

The API will return an error, because ```querystring.stringify()``` will render the JSON array as an empty property (```...&take_profit_step_orders=&...```).

```
{ error: 'record_invalid',
  error_description: 'Invalid parameters',
  error_attributes:
   { 'take_profit_step_orders[percent]': [ 'is missing' ],
     'take_profit_step_orders[price_method]': [ 'is missing' ] } }
```

**Comment by rentorm** [comment]
I'll have to look in to it, however, strage is that it is not complaining about `price`, does it mean this part is being passed correctly?

**Comment by mamash** [comment]
In no case the API complained about the price missing. However, maybe this attribute is handled subsequently or in a different way, since it's either ```price``` *or* ```price_percentage```.

**Comment by MoroZvlg** [comment]
@mamash as i see `querystring` library can't swallow such complicated things as steps(array of objects)
![image](https://user-images.githubusercontent.com/30448147/58767216-0872bc80-8591-11e9-9fa7-78ac26853271.png)
But if i use `JSON.stringify` on steps before pass parameters to `querystring.stringify` it will work for me
![image](https://user-images.githubusercontent.com/30448147/58767655-61ddea00-8597-11e9-9fa6-6167eac60376.png)
I'm sure you guys will fix it without such kludge.(I never used node js, only this sample)

About price - it's optional parameter because of trailing buy possibility. It will validates on next step - that's why there is no "price is missing error" error, but it's missing too.

I understand that this is definitely not obvious. I think we will fix such mistakes in future versions. Sorry

**Comment by mamash** [comment]
As suggested by @MoroZvlg above, stringifying the array is enough to make this work. Yay! Totally not sure if this is worth implementing on this end though. This can be closed from my point of view.
